package com.psc.view.frmproduto;

import com.psc.dao.CategoriaDAO;
import com.psc.dao.ProdutoDAO;
import com.psc.model.Categoria;
import com.psc.model.Produto;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.List;

/**
 * @author Gabriel
 */
public class FrmEditarProdutos extends javax.swing.JFrame {

    ProdutoDAO produtoDAO = new ProdutoDAO();
    CategoriaDAO categoriaDAO = new CategoriaDAO();

    /**
     * Creates new form FrmEditarProdutos
     */
    public FrmEditarProdutos() {
        initComponents();
        carregarTabela();
        carregarCategorias();
    }

    private void carregarCategorias() {
        List<Categoria> categorias = categoriaDAO.listar();

        DefaultComboBoxModel<String> modelo = new DefaultComboBoxModel<>();
        for (Categoria cat : categorias) {
            modelo.addElement(cat.toString());
        }
        JCBCategoria.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    public final void carregarTabela() {
        DefaultTableModel modelo = (DefaultTableModel) this.TableProdutos.getModel();
        modelo.setRowCount(0); // limpa as linhas da tabela

        // Pega os dados do banco ou lista
        for (Produto p : produtoDAO.listar()) {
            modelo.addRow(new Object[]{
                    p.getId(),
                    p.getNome(),
                    p.getPrecoUnitario(),
                    p.getUnidade(),
                    p.getQuantidadeEstoque(),
                    p.getQuantidadeMinima(),
                    p.getQuantidadeMaxima(),
                    p.getCategoria().toString()
            });
        }
    }

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TableProdutos = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        JTFNome = new javax.swing.JTextField();
        JTFId = new javax.swing.JTextField();
        JTFatual = new javax.swing.JTextField();
        JTFmaxima = new javax.swing.JTextField();
        JTFpreco = new javax.swing.JTextField();
        JTFminima = new javax.swing.JTextField();
        JBAlterar = new javax.swing.JToggleButton();
        JBApagar = new javax.swing.JToggleButton();
        jToggleButton6 = new javax.swing.JToggleButton();
        JCBUnidade = new javax.swing.JComboBox<>();
        JBReajustarPrecos = new javax.swing.JToggleButton();
        JCBCategoria = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Edição de produtos");

        TableProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nome", "Preço por unidade ", "Tipo da unidade", "Quantidade atual", "Quantidade mínima", "Quantidade máxima", "Categoria"
            }
        ));
        TableProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableProdutosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableProdutos);

        jLabel4.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jLabel4.setText("Nome:");

        jLabel6.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jLabel6.setText("Preço por unidade:");

        jLabel7.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jLabel7.setText("Tipo da unidade:");

        jLabel8.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jLabel8.setText("Quantidade atual em estoque:");

        jLabel9.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jLabel9.setText("Quantidade mínima em estoque:");

        jLabel10.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jLabel10.setText("Quantidade máxima em estoque:");

        jLabel11.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jLabel11.setText("Categoria:");

        JTFNome.setFont(new java.awt.Font("Fira Sans", 0, 14)); // NOI18N
        JTFNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFNomeActionPerformed(evt);
            }
        });

        JTFId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFIdActionPerformed(evt);
            }
        });

        JTFatual.setFont(new java.awt.Font("Fira Sans", 0, 14)); // NOI18N
        JTFatual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFatualActionPerformed(evt);
            }
        });

        JTFmaxima.setFont(new java.awt.Font("Fira Sans", 0, 14)); // NOI18N
        JTFmaxima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFmaximaActionPerformed(evt);
            }
        });

        JTFpreco.setFont(new java.awt.Font("Fira Sans", 0, 14)); // NOI18N
        JTFpreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFprecoActionPerformed(evt);
            }
        });

        JTFminima.setFont(new java.awt.Font("Fira Sans", 0, 14)); // NOI18N
        JTFminima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFminimaActionPerformed(evt);
            }
        });

        JBAlterar.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        JBAlterar.setText("Alterar");
        JBAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBAlterarActionPerformed(evt);
            }
        });

        JBApagar.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        JBApagar.setText("Apagar");
        JBApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBApagarActionPerformed(evt);
            }
        });

        jToggleButton6.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jToggleButton6.setText("Voltar");
        jToggleButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton6ActionPerformed(evt);
            }
        });

        JCBUnidade.setFont(new java.awt.Font("Fira Sans", 0, 14)); // NOI18N
        JCBUnidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "UN", "KG", "G", "L", "ML" }));
        JCBUnidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCBUnidadeActionPerformed(evt);
            }
        });

        JBReajustarPrecos.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        JBReajustarPrecos.setText("<html>Alterar o valor de  <br> todos os produtos</html>");
        JBReajustarPrecos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBReajustarPrecosActionPerformed(evt);
            }
        });

        JCBCategoria.setFont(new java.awt.Font("Fira Sans", 0, 14)); // NOI18N
        JCBCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCBCategoriaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 0, 36)); // NOI18N
        jLabel1.setText("Gerenciamento de Produtos existentes");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1027, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JTFId, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(JTFNome, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6)
                                .addComponent(JTFpreco, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4)
                                .addComponent(JCBUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8)
                                .addComponent(JTFminima, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10))
                            .addComponent(jLabel9)
                            .addComponent(jLabel7)
                            .addComponent(JTFatual, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTFmaxima, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(JCBCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(JBApagar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JBReajustarPrecos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(JBAlterar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToggleButton6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addComponent(JTFId, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JTFNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTFpreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JCBUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JBAlterar)
                        .addGap(18, 18, 18)
                        .addComponent(JBApagar)
                        .addGap(18, 18, 18)
                        .addComponent(JBReajustarPrecos, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButton6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JTFatual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JTFminima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JTFmaxima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JCBCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTFNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFNomeActionPerformed

    private void JTFatualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFatualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFatualActionPerformed

    private void JTFmaximaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFmaximaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFmaximaActionPerformed

    private void JTFprecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFprecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFprecoActionPerformed

    private void JTFminimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFminimaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFminimaActionPerformed

    private void JBAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBAlterarActionPerformed
        // TODO add your handling code here:
        try {
            int id = Integer.parseInt(this.JTFId.getText());
            String nome = this.JTFNome.getText();
            double precoUnitario = Double.parseDouble(this.JTFpreco.getText());
            String unidade = (String) this.JCBUnidade.getSelectedItem();
            int quantidadeEstoque = Integer.parseInt(this.JTFatual.getText());
            int quantidadeMinima = Integer.parseInt(this.JTFminima.getText());
            int quantidadeMaxima = Integer.parseInt(this.JTFmaxima.getText());
            String categoria = this.JCBCategoria.getSelectedItem().toString();
            int categoriaId = 0;
            String categoriaNome = "";

            // Validações simples
            if (nome.length() < 2) {
                throw new IllegalArgumentException("Nome deve conter ao menos 2 caracteres.");
            }
            if (precoUnitario <= 0) {
                throw new IllegalArgumentException("Preço unitário deve ser maior que zero.");
            }

            if (quantidadeEstoque < 0 || quantidadeMinima < 0 || quantidadeMaxima < 0) {
                throw new IllegalArgumentException("As quantidades não podem ser negativas.");
            }

            if (categoria != null && categoria.contains(" - ")) {
                String[] partes = categoria.split(" - ", 2); // limita a 2 partes
                categoriaId = Integer.parseInt(partes[0].trim());
                categoriaNome = partes[1].trim();
            }

            Categoria cat = new Categoria(categoriaId, categoriaNome);

            // Criação do produto
            Produto p = new Produto(id, nome, precoUnitario, unidade, quantidadeEstoque, quantidadeMinima, quantidadeMaxima, cat);

            // Atualiza no banco de dados
            produtoDAO.atualizar(p);
            carregarTabela();

            JOptionPane.showMessageDialog(null, "Produto atualizado com sucesso!");

            // Limpa os campos após cadastro
            this.JTFId.setText("");
            this.JTFNome.setText("");
            this.JTFpreco.setText("");
            this.JTFatual.setText("");
            this.JTFminima.setText("");
            this.JTFmaxima.setText("");

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Preencha os campos numéricos corretamente.", "Erro", JOptionPane.ERROR_MESSAGE);
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        } finally {
            carregarTabela(); // Recarrega a tabela com os dados atualizados
        }
    }//GEN-LAST:event_JBAlterarActionPerformed


    private void JBApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBApagarActionPerformed
        // TODO add your handling code here:
        try {
            int id = 0;

            if (this.TableProdutos.getSelectedRow() == -1) {
                throw new Exception("Primeiro selecione um Produto para APAGAR");
            } else {
                id = Integer.parseInt(this.TableProdutos
                        .getValueAt(this.TableProdutos.getSelectedRow(), 0).toString());
            }

            int respostaUsuario = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja apagar este Produto?");

            if (respostaUsuario == 0) { // clicou em SIM

                if (this.produtoDAO.deletar(id)) {
                    // Limpa os campos
                    this.JTFId.setText("");
                    this.JTFNome.setText("");
                    this.JTFpreco.setText("");
                    this.JTFatual.setText("");
                    this.JTFminima.setText("");
                    this.JTFmaxima.setText("");

                    JOptionPane.showMessageDialog(null, "Produto apagado com sucesso!");
                }
            }
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        } finally {
            carregarTabela(); // Recarrega a tabela com os dados atualizados
        }
    }//GEN-LAST:event_JBApagarActionPerformed

    private void jToggleButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton6ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jToggleButton6ActionPerformed

    private void TableProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableProdutosMouseClicked
        // TODO add your handling code here:
        if (this.TableProdutos.getSelectedRow() != -1) {
            String id = this.TableProdutos.getValueAt(this.TableProdutos.getSelectedRow(), 0).toString();
            String nome = this.TableProdutos.getValueAt(this.TableProdutos.getSelectedRow(), 1).toString();
            String preco = this.TableProdutos.getValueAt(this.TableProdutos.getSelectedRow(), 2).toString();
            String unidade = this.TableProdutos.getValueAt(this.TableProdutos.getSelectedRow(), 3).toString();
            String estoque = this.TableProdutos.getValueAt(this.TableProdutos.getSelectedRow(), 4).toString();
            String minima = this.TableProdutos.getValueAt(this.TableProdutos.getSelectedRow(), 5).toString();
            String maxima = this.TableProdutos.getValueAt(this.TableProdutos.getSelectedRow(), 6).toString();
            String categoria = TableProdutos.getValueAt(TableProdutos.getSelectedRow(), 7).toString();

            this.JTFId.setText(id);
            this.JTFNome.setText(nome);
            this.JTFpreco.setText(preco);
            this.JCBUnidade.setSelectedItem(unidade);
            this.JTFatual.setText(estoque);
            this.JTFminima.setText(minima);
            this.JTFmaxima.setText(maxima);
            for (int i = 0; i < JCBCategoria.getItemCount(); i++) {
                String item = JCBCategoria.getItemAt(i);
                if (item.equals(categoria)) {
                    JCBCategoria.setSelectedIndex(i);
                    break;
                }
            }
        }
    }//GEN-LAST:event_TableProdutosMouseClicked

    private void JBReajustarPrecosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBReajustarPrecosActionPerformed
        // TODO add your handling code here:
        try {
            String input = JOptionPane.showInputDialog("Digite o percentual de aumento (ex: 10 para 10%):");
            if (input == null || input.trim().isEmpty()) {
                return; // Cancelado
            }

            double percentual = Double.parseDouble(input);

            // Chama o DAO para atualizar os preços no banco
            ProdutoDAO dao = new ProdutoDAO();
            boolean ok = dao.reajustarPrecos(percentual);

            if (ok) {
                JOptionPane.showMessageDialog(null, "Preços reajustados com sucesso!");
                this.carregarTabela(); // Atualiza a tabela se tiver esse método
            } else {
                JOptionPane.showMessageDialog(null, "Erro ao reajustar preços.");
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Digite um número válido para o percentual.");
        }
    }//GEN-LAST:event_JBReajustarPrecosActionPerformed

    private void JTFIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFIdActionPerformed

    private void JCBUnidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCBUnidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JCBUnidadeActionPerformed

    private void JCBCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCBCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JCBCategoriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmEditarProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmEditarProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmEditarProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmEditarProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FrmEditarProdutos().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton JBAlterar;
    private javax.swing.JToggleButton JBApagar;
    private javax.swing.JToggleButton JBReajustarPrecos;
    private javax.swing.JComboBox<String> JCBCategoria;
    private javax.swing.JComboBox<String> JCBUnidade;
    private javax.swing.JTextField JTFId;
    private javax.swing.JTextField JTFNome;
    private javax.swing.JTextField JTFatual;
    private javax.swing.JTextField JTFmaxima;
    private javax.swing.JTextField JTFminima;
    private javax.swing.JTextField JTFpreco;
    private javax.swing.JTable TableProdutos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton6;
    // End of variables declaration//GEN-END:variables
}
