package com.psc.view.frmproduto;

/**
 * Janela principal para gerenciamento de produtos.
 *
 * <p>Permite acesso às funcionalidades de criação e edição de produtos,
 * bem como o fechamento da janela atual.</p>
 *
 * <p>Esta interface é uma ponte entre a navegação do sistema e as
 * janelas {@link FrmCriarProduto} e {@link FrmEditarProdutos}.</p>
 *
 * @author Machadox18
 */
public class FrmGerenciarProdutos extends javax.swing.JFrame {

    /**
     * Construtor padrão que inicializa os componentes da interface gráfica.
     */
    public FrmGerenciarProdutos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JBCriarproduto = new javax.swing.JToggleButton();
        JBEditarprodutos = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JBCriarproduto.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        JBCriarproduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/h32create_product.png"))); // NOI18N
        JBCriarproduto.setText("Criar Produto");
        JBCriarproduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBCriarprodutoActionPerformed(evt);
            }
        });

        JBEditarprodutos.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        JBEditarprodutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FRAMEedit_product.png"))); // NOI18N
        JBEditarprodutos.setText("Editar Produto");
        JBEditarprodutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBEditarprodutosActionPerformed(evt);
            }
        });

        jToggleButton2.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jToggleButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FRAMEhome.png"))); // NOI18N
        jToggleButton2.setText("Sair");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(JBCriarproduto, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(JBEditarprodutos, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(100, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(283, 283, 283))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(206, 206, 206)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(JBCriarproduto, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(JBEditarprodutos, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 168, Short.MAX_VALUE)
                                .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Ação executada ao clicar no botão "Criar Produto".
     *
     * <p>Abre a janela {@link FrmCriarProduto} para cadastrar um novo produto.</p>
     *
     * @param evt Evento de clique do botão
     */
    private void JBCriarprodutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBCriarprodutoActionPerformed
        FrmCriarProduto janelaCriarProduto = new FrmCriarProduto();
        janelaCriarProduto.setVisible(true);
    }//GEN-LAST:event_JBCriarprodutoActionPerformed

    /**
     * Ação executada ao clicar no botão "Editar Produtos".
     *
     * <p>Abre a janela {@link FrmEditarProdutos} para editar produtos já existentes.</p>
     *
     * @param evt Evento de clique do botão
     */
    private void JBEditarprodutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBEditarprodutosActionPerformed
        FrmEditarProdutos janelaEditarProdutos = new FrmEditarProdutos();
        janelaEditarProdutos.setVisible(true);
    }//GEN-LAST:event_JBEditarprodutosActionPerformed

    /**
     * Ação executada ao clicar no botão "Fechar" (jToggleButton2).
     *
     * <p>Fecha a janela atual de gerenciamento de produtos.</p>
     *
     * @param evt Evento de clique do botão
     */
    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        this.dispose(); // Fecha a janela
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmGerenciarProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmGerenciarProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmGerenciarProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmGerenciarProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmGerenciarProdutos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton JBCriarproduto;
    private javax.swing.JToggleButton JBEditarprodutos;
    private javax.swing.JToggleButton jToggleButton2;
    // End of variables declaration//GEN-END:variables
}
